### ISSUE TITLE
Use fp_sampling for default OpenPCDet repo

### ISSUE THREAD

**Issue by Petros626** [KaAI-KMU/Openpcdet_Sampling#5]
Hey, 

I stepped over this paper here: "False Positive Sampling-based Data Augmentation for Enhanced 3D Object Detection Accuracy" and would like to know how to activate fp_sampling during a normal training process.

Would it be in `kitti_dataset.yaml` like that?
```yaml
 - NAME: fp_sampling 
   USE_ROAD_PLANE: True
   DB_INFO_PATH:
       - kitti_dbinfos_train.pkl
   PREPARE: {
       filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5'],
       filter_by_difficulty: [-1],
   }
   SAMPLE_GROUPS: ['Car:20','Pedestrian:15', 'Cyclist:15']
   NUM_POINT_FEATURES: 4
   DATABASE_WITH_FAKELIDAR: False
   REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
   LIMIT_WHOLE_SCENE: True
```
Thanks in advance
